config/routes.rb
Rails.application.routes.draw do
  root to: "lists#index"
  resources :books, only: [:index]
  resources :lists, except: :index do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :lists
  has_many :bookmarks
  has_one_attached :photo

  # validates :title, :description, uniqueness: true
  # validates :title, :description, presence: true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :book

  validates :book_id, uniqueness: { scope: :list_id }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :books, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :book_id, :list_id)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show edit update destroy]
  
  def index
    @lists = List.all
  end

  def show
    @books = Book.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    @list.update(list_params)
    redirect_to list_path(@list)
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :book %>
    <%= f.submit %>
  <% end %>
</div>

app/views/books/index.html.erb
<div class="container p-4">
  <% @books.each do |book| %>
    <div class="d-flex justify-content-between p-3 mb-2 shadow bg-white">
      <h4><%= book.title %></h4>
      <%= image_tag "https://books.toscrape.com/#{book.image_url}", width: 100 %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CertifPractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>

  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <script>
      AOS.init();
    </script>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/lists/edit.html.erb
<div class="container p-5">
  <%= render "form", list: @list %>
</div>

app/views/lists/index.html.erb
<div class="container">
  <h1 class="fw-bolder mb-3 text-center">My lists</h1>
  <% @lists.each do |list| %>
    <div class="card-category mt-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>')">
      <%= link_to list.name, list_path(list), class: "text-decoration-none text-white" %>
    </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<div class="container p-5">
  <%= render "form", list: @list %>
</div>

app/views/lists/show.html.erb
<div class="container">
  <div class="d-flex justify-content-center flex-column align-items-center">
    <h1 class='mt-2 fw-bolder'><%= @list.name %></h1>
    <br>
    <div class="links d-flex justify-content-around">
      <%= link_to new_list_bookmark_path(@list), class: 'btn btn-ghost rounded-pill mx-2' do %>
        <i class="fa-solid fa-plus"></i>
      <% end %>
      <%= link_to list_path(@list),
        data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
        class: 'btn btn-ghost rounded-pill mx-2' do
      %>
        <i class="fa-solid fa-trash-can"></i>
      <% end %>
      <%= link_to edit_list_path(@list), class: 'btn btn-ghost rounded-pill' do %>
        <i class="fa-solid fa-pencil"></i>
      <% end %>
    </div>
  </div>


  <div class="mt-3 cards-books text-center d-flex justify-content-center">
    <% @list.books.each do |book| %>
      <%# <div data-aos="zoom-out-up"> %>
        <div class="card-book shadow-lg mb-3" style="background-image: url('https://books.toscrape.com/<%= book.image_url %>')" id="hello">
          <div class="overlay"></div>
          <div class="book-info"><h4><%= book.title %></h4></div>
          <div class="book-info-card bg-white p-2 ">
            <p  class="text-ellipsis"><em><%= book.bookmarks.first.comment %></em></p>
          </div>
        </div>
      <%# </div> %>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "new list", new_list_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>